#!/bin/sh

set -e

command -v cmake > /dev/null || { echo >&2 "To build kostak we need CMake. Aborting"; exit 1; }
# command -v gcc > /dev/null || { echo >&2 "You don't even have compiler. Please install gcc"; exit 1; }

EXTRA_DEFS=""

OSNAME=$(uname -s)
PROCESSOR=$(uname -m)

TARGET_TUPLE="x86_64-kostak-linux-musl"

if test "x${OSNAME}" != "xLinux"
then
  echo "The build computer is not linux, cross-compiling"
  EXTRA_DEFS="${EXTRA_DEFS} -DKOSTAK_TOOLCHAIN_DIR=$(dirname $(dirname $(which $TARGET_TUPLE-gcc)))"
  EXTRA_DEFS="${EXTRA_DEFS} -DKOSTAK_STATIC=1"
  EXTRA_DEFS="${EXTRA_DEFS} -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-kostak-linux-amd64.cmake"
fi

  

function do_build() {
  mkdir -p build/{bin,lib} && cd build
  if command -v ninja > /dev/null; then
    echo >&2 "Ninja found, using ninja build tools"
    cmake ${EXTRA_DEFS} -G "Ninja" .. && ninja 
  else
    command -v make > /dev/null || { echo >&2 "Please install make. Aborting"; exit 1; }
    cmake ${EXTRA_DEFS} -G "Unix Makefiles" .. && make
  fi
  cd ..
}

case $1 in
  clean)
    rm -rf build/*
    ;;
  small)
    EXTRA_DEFS="${EXTRA_DEFS} -DCMAKE_BUILD_TYPE=MinSizeRel"
    do_build
    strip build/bin/kostak 
    ;;
  smatic)
    EXTRA_DEFS="${EXTRA_DEFS} -DCMAKE_BUILD_TYPE=MinSizeRel -DKOSTAK_STATIC=1"
    do_build
    strip build/bin/kostak
    ;;
  static)
    EXTRA_DEFS="${EXTRA_DEFS} -DKOSTAK_STATIC=1"
    do_build
    ;;
  *)
    do_build
    ;;
esac
